name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scans weekly
    - cron: '0 6 * * 1'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  lint:
    name: Lint & Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.2.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning

      - name: Validate docker-compose.yml
        run: |
          # Install docker-compose
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          docker-compose config -q

      - name: Check Makefile syntax
        run: |
          make help || echo "Make not available in runner"

      - name: Validate environment files
        run: |
          # Check .env.example syntax
          if [ -f .env.example ]; then
            echo "Validating .env.example..."
            # Simple syntax validation
            grep -E '^[A-Z_][A-Z0-9_]*=' .env.example || true
          fi

  test-build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VERSION=test-${{ github.sha }}
            VCS_REF=${{ github.sha }}
            TANDOOR_VERSION=1.5.19
            PROJECT_VERSION=$(cat VERSION || echo "1.0.0")

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: mildman1848/tandoor:test
          cache-from: type=gha
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VERSION=test
            VCS_REF=${{ github.sha }}
            PROJECT_VERSION=$(cat VERSION || echo "1.0.0")

      - name: Create test environment
        run: |
          # Create test directories for tandoor with proper structure
          mkdir -p test-volumes/config/{tandoor,cache,logs}
          mkdir -p test-volumes/{data,media,backup}

          # Set proper permissions for directories
          chmod 755 test-volumes/config
          chmod 755 test-volumes/data test-volumes/media test-volumes/backup

          # Create minimal .env for testing
          cat > .env << EOF
          DOCKER_REPO=mildman1848/tandoor
          VERSION=test
          PUID=1000
          PGID=1000
          TZ=UTC
          TANDOOR_LOG_LEVEL=INFO
          TANDOOR_MODE=server
          EXTERNAL_PORT=8080
          EOF

      - name: Generate test secrets
        run: |
          mkdir -p secrets
          openssl rand -base64 32 | tr -d "=+/" | head -c 24 > secrets/tandoor_config_pass.txt
          openssl rand -base64 32 | tr -d "=+/" | head -c 32 > secrets/tandoor_api_key.txt
          openssl rand -base64 48 | tr -d "=+/" | head -c 48 > secrets/tandoor_jwt_secret.txt
          chmod 600 secrets/*.txt

      - name: Test container startup
        run: |
          # Start container
          docker run -d \
            --name tandoor-test \
            -p 8080:8080 \
            -v $(pwd)/test-volumes/config:/config \
            -v $(pwd)/test-volumes/data:/data \
            -v $(pwd)/test-volumes/media:/media \
            -v $(pwd)/test-volumes/backup:/backup \
            -v $(pwd)/secrets:/run/secrets:ro \
            -e PUID=1000 \
            -e PGID=1000 \
            -e TZ=UTC \
            -e TANDOOR_MODE=server \
            -e FILE__TANDOOR_API_KEY=/run/secrets/tandoor_api_key.txt \
            mildman1848/tandoor:test

      - name: Wait for container
        run: |
          # Wait for container to be ready - improved startup detection
          echo "Waiting for container to start..."
          sleep 10

          # Wait for tandoor process to start
          timeout 180s bash -c 'while ! docker exec tandoor-test ps aux | grep -v grep | grep tandoor >/dev/null 2>&1; do
            echo "Waiting for tandoor process..."
            sleep 5
          done'

          # Additional wait for application to be ready
          echo "Waiting for application to be ready..."
          sleep 20

      - name: Test container health
        run: |
          # Check if container is running
          docker ps | grep tandoor-test

          # Test tandoor process is running
          docker exec tandoor-test ps aux | grep -v grep | grep tandoor

          # Check container logs for any errors
          echo "=== Container startup logs ==="
          docker logs tandoor-test

          # Test basic connectivity
          echo "=== Testing basic connectivity ==="
          timeout 30s bash -c 'while ! nc -z localhost 8080; do echo "Waiting for port 8080..."; sleep 2; done' || echo "Port 8080 check timed out"

          # Application-specific health checks
          ${APPLICATION_SPECIFIC_HEALTH_CHECKS}

      - name: Test container logs
        if: always()
        run: |
          echo "=== Container logs ==="
          docker logs tandoor-test
          echo "=== Container inspect ==="
          docker inspect tandoor-test

      - name: Cleanup test container
        if: always()
        run: |
          docker stop tandoor-test || true
          docker rm tandoor-test || true

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for scanning
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: mildman1848/tandoor:scan
          cache-from: type=gha

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mildman1848/tandoor:scan'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy for detailed output
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mildman1848/tandoor:scan'
          format: 'table'
          exit-code: '0'  # Don't fail the build on vulnerabilities

  docker-compose-test:
    name: Docker Compose Test
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install docker-compose
        run: |
          # Install docker-compose
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Create test environment
        run: |
          # Create test directories for docker-compose
          mkdir -p config/{tandoor,cache,logs}
          mkdir -p data media backup logs
          chmod 755 config data media backup logs

          # Copy .env.example to .env for testing
          cp .env.example .env

          # Override with test values for docker-compose
          cat >> .env << EOF
          VERSION=test
          IMAGE_TAG=test
          EXTERNAL_PORT=8080
          TANDOOR_LOG_LEVEL=DEBUG
          CONFIG_PATH=./config
          DATA_PATH=./data
          MEDIA_PATH=./media
          BACKUP_PATH=./backup
          LOGS_PATH=./logs
          SECRETS_PATH=./secrets
          EOF

      - name: Generate secrets
        run: |
          mkdir -p secrets
          openssl rand -base64 32 | tr -d "=+/" | head -c 24 > secrets/tandoor_config_pass.txt
          openssl rand -base64 32 | tr -d "=+/" | head -c 32 > secrets/tandoor_api_key.txt
          openssl rand -base64 48 | tr -d "=+/" | head -c 48 > secrets/tandoor_jwt_secret.txt

      - name: Build image first
        run: |
          docker build -t mildman1848/tandoor:test .

      - name: Test docker-compose up
        run: |
          # The IMAGE_TAG=test is already set in .env file
          docker-compose up -d tandoor

      - name: Wait and test service
        run: |
          # Wait for service startup and check container status
          echo "Waiting for tandoor service to start..."
          sleep 20

          # Check container status first
          echo "=== Container status ==="
          docker-compose ps

          # Check container logs early to debug issues
          echo "=== Container logs ==="
          docker-compose logs tandoor

          # Wait for container to be healthy (more robust approach)
          echo "Waiting for container to be ready..."
          for i in {1..30}; do
            if docker-compose ps tandoor | grep -q "Up"; then
              echo "Container is running, checking health..."
              break
            fi
            echo "Container not ready yet, waiting... ($i/30)"
            sleep 5
          done

          # Test if tandoor process is running (only if container is up)
          echo "=== Checking tandoor process ==="
          if docker-compose ps tandoor | grep -q "Up"; then
            docker-compose exec -T tandoor ps aux | grep -v grep | grep tandoor || echo "tandoor process not found yet"
          else
            echo "Container is not running - skipping process check"
          fi

          # Test basic connectivity
          echo "=== Testing port connectivity ==="
          timeout 60s bash -c 'while ! nc -z localhost 8080; do echo "Waiting for port 8080..."; sleep 3; done' || echo "Port check timed out"

          # Application-specific service tests
          ${APPLICATION_SPECIFIC_SERVICE_TESTS}

      - name: Check logs
        if: always()
        run: |
          echo "=== Docker Compose logs ==="
          docker-compose logs

      - name: Cleanup
        if: always()
        run: |
          docker-compose down -v