---
# Security hardening override (automatically applied by docker-compose)
# This file provides comprehensive security hardening for all Mildman1848 containers
# Based on Docker Security Best Practices and LinuxServer.io standards

services:
  tandoor:
    # Enhanced security options
    security_opt:
      - no-new-privileges:true
      - apparmor=docker-default
      # seccomp profile temporarily disabled due to compatibility issues
      # - seccomp=./security/seccomp-profile.json

    # Comprehensive capability management (temporarily disabled)
    # cap_drop:
    #   - ALL
    # cap_add:
    #   - SETGID      # User switching (LinuxServer.io requirement)
    #   - SETUID      # User switching (LinuxServer.io requirement)
    #   - CHOWN       # File ownership management
    #   - DAC_OVERRIDE # File access (minimal)
    #   - FOWNER      # File ownership operations

    # Resource limits for security and stability
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
          pids: 200
        reservations:
          cpus: '0.25'
          memory: 128M

    # tmpfs mounts for security (temporarily disabled)
    # tmpfs:
    #   - /tmp:rw,noexec,nosuid,size=100m
    #   - /var/tmp:rw,noexec,nosuid,size=50m
    #   - /run:rw,noexec,nosuid,size=50m

    # Enhanced logging for security monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=tandoor,environment=development"

    # Additional security environment variables
    environment:
      # Security hardening
      - UMASK=027                    # Restrictive file permissions
      - CORE_DUMP_SIZE=0            # Disable core dumps
      - DNS=1.1.1.1,8.8.8.8        # Secure DNS servers

      # Audit and monitoring
      - AUDIT_ENABLED=true          # Enable audit logging
      - DEBUG_MODE=false            # Disable debug mode for security

    # Additional volume security options
    volumes:
      # Override config volume with additional security
      - ${CONFIG_PATH:-./config}:/config:rw,Z
      - ${DATA_PATH:-./data}:/data:rw,Z
      - ${LOGS_PATH:-./logs}:/config/logs:rw,Z