---
# Production configuration with maximum security
# Use: docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d

services:
  tandoor:
    # Production-grade security
    security_opt:
      - no-new-privileges:true
      - apparmor=docker-default
      - seccomp=./security/seccomp-profile.json

    # Localhost-only binding for maximum security
    ports:
      - "127.0.0.1:${EXTERNAL_PORT:-8080}:8080"

    # Production resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
          pids: 100
        reservations:
          cpus: '0.5'
          memory: 256M

    # Read-only volumes where possible
    volumes:
      - ${CONFIG_PATH:-./config}:/config:ro,Z     # Read-only config
      - ${DATA_PATH:-./data}:/data:rw,Z           # Read-write data
      - ${LOGS_PATH:-./logs}:/config/logs:rw,Z    # Read-write logs

    # Production logging with structured format
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        labels: "service=tandoor,environment=production"

    # Production environment variables
    environment:
      # Security
      - LOG_LEVEL=INFO              # Production log level
      - DEBUG_MODE=false            # Disable debug
      - AUDIT_ENABLED=true          # Enable audit logging

      # Performance
      - TANDOOR_WORKERS=2          # Production worker count
      - TANDOOR_CACHE_ENABLED=true # Enable caching

      # Security hardening
      - UMASK=027                   # Restrictive permissions
      - CORE_DUMP_SIZE=0           # Disable core dumps
      - TMPDIR=/tmp                # Secure temp directory

    # Enhanced tmpfs for production
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=50m
      - /var/tmp:rw,noexec,nosuid,nodev,size=25m
      - /run:rw,noexec,nosuid,nodev,size=25m

    # Production health check (more frequent)
    healthcheck:
      test: ["CMD", "pgrep", "-f", "tandoor"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s

    # Production labels
    labels:
      - "org.opencontainers.image.title=tandoor"
      - "org.opencontainers.image.description=Tandoor Recipes - Recipe management server with S6 Overlay"
      - "org.opencontainers.image.vendor=Mildman1848"
      - "environment=production"
      - "security.level=high"

# Production network with custom settings
networks:
  default:
    name: tandoor_production_network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"