---
# docker-compose.override.yml
# PostgreSQL Database Extension for Tandoor Recipes
#
# This file adds PostgreSQL support to the base docker-compose.yml
# To use PostgreSQL instead of SQLite3:
# 1. Run: make secrets-generate (or make secrets-django for Django-optimized secrets)
# 2. Start with: docker compose up -d
#
# Docker Compose automatically applies override files when present.

services:
  tandoor:
    # Add PostgreSQL environment configuration
    environment:
      # Database configuration (PostgreSQL)
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=${POSTGRES_HOST:-db_recipes}
      - POSTGRES_DB=${POSTGRES_DB:-djangodb}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}

      # PostgreSQL secrets support
      - FILE__POSTGRES_PASSWORD=/run/secrets/tandoor_postgres_password
      - FILE__POSTGRES_USER=/run/secrets/tandoor_postgres_user

    # Add PostgreSQL secrets
    secrets:
      - tandoor_secret_key
      - tandoor_postgres_password
      - tandoor_postgres_user

    # Add PostgreSQL dependency
    depends_on:
      db_recipes:
        condition: service_healthy

  # PostgreSQL Database service
  db_recipes:
    image: postgres:16-alpine
    container_name: tandoor_db
    hostname: db_recipes
    restart: unless-stopped

    # Security hardening
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID

    environment:
      - POSTGRES_DB=${POSTGRES_DB:-djangodb}
      # PostgreSQL secrets support (uses _FILE suffix exclusively)
      # Note: Cannot use both POSTGRES_PASSWORD and POSTGRES_PASSWORD_FILE
      - POSTGRES_PASSWORD_FILE=/run/secrets/tandoor_postgres_password
      - POSTGRES_USER_FILE=/run/secrets/tandoor_postgres_user

    volumes:
      - ${DB_DATA_PATH:-./data/db}:/var/lib/postgresql/data

    # Docker secrets support for PostgreSQL
    secrets:
      - tandoor_postgres_password
      - tandoor_postgres_user

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d djangodb -U $(cat /run/secrets/tandoor_postgres_user)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    # Labels for better organization
    labels:
      - "org.opencontainers.image.title=tandoor-db"
      - "org.opencontainers.image.description=PostgreSQL database for Tandoor Recipes"
      - "org.opencontainers.image.vendor=Mildman1848"

# PostgreSQL secrets (extend base secrets)
secrets:
  tandoor_secret_key:
    file: ${SECRETS_PATH:-./secrets}/tandoor_secret_key.txt
  tandoor_postgres_password:
    file: ${SECRETS_PATH:-./secrets}/tandoor_postgres_password.txt
  tandoor_postgres_user:
    file: ${SECRETS_PATH:-./secrets}/tandoor_postgres_user.txt