#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Display Mildman1848 ASCII art branding
cat /etc/s6-overlay/s6-rc.d/init-adduser/branding

echo "Mildman1848 ${APPLICATION_NAME} branding configured successfully"