---
services:
  tandoor:
    image: ${IMAGE_NAME:-mildman1848/tandoor}:${IMAGE_TAG:-latest}
    container_name: tandoor
    hostname: tandoor
    restart: unless-stopped

    # Security hardening (basic)
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID

    # Network configuration
    ports:
      - "${HOST:-127.0.0.1}:${EXTERNAL_PORT:-8080}:8080"

    # Environment configuration
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - UMASK=${UMASK:-022}

      # tandoor specific environment variables
      - TANDOOR_MODE=${TANDOOR_MODE:-server}
      - TANDOOR_CONFIG=/config/tandoor/tandoor.conf
      - TANDOOR_CACHE_DIR=/config/cache
      - TANDOOR_TEMP_DIR=/tmp/tandoor
      - TANDOOR_LOG_LEVEL=${TANDOOR_LOG_LEVEL:-INFO}
      - TANDOOR_LOG_FILE=/config/logs/tandoor.log

      # Security configuration
      - TANDOOR_NO_AUTH=${TANDOOR_NO_AUTH:-false}
      - HOST=${HOST:-127.0.0.1}

      # Optional: FILE__ prefix secrets support
      - FILE__TANDOOR_CONFIG_PASS=/run/secrets/tandoor_config_pass
      - FILE__TANDOOR_PASSWORD
      - FILE__TANDOOR_API_KEY=/run/secrets/tandoor_api_key

      # Additional application configuration
      ${ADDITIONAL_ENVIRONMENT_VARIABLES}

    # Volume mounts
    volumes:
      - ${CONFIG_PATH:-./config}:/config
      - ${DATA_PATH:-./data}:/data
      - ${LOGS_PATH:-./logs}:/config/logs
      # Mount additional paths as needed
      - ${MEDIA_PATH:-./media}:/media
      - ${BACKUP_PATH:-./backup}:/backup

    # Optional: Docker secrets support
    secrets:
      - tandoor_config_pass
      - tandoor_api_key
      - tandoor_jwt_secret

    # Health check (process-based for security)
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep -v grep | grep tandoor || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Labels for better organization
    labels:
      - "org.opencontainers.image.title=tandoor"
      - "org.opencontainers.image.description=Tandoor Recipes - Recipe management server with S6 Overlay"
      - "org.opencontainers.image.vendor=Mildman1848"

# Docker secrets (optional)
secrets:
  tandoor_config_pass:
    file: ${SECRETS_PATH:-./secrets}/tandoor_config_pass.txt
  tandoor_api_key:
    file: ${SECRETS_PATH:-./secrets}/tandoor_api_key.txt
  tandoor_jwt_secret:
    file: ${SECRETS_PATH:-./secrets}/tandoor_jwt_secret.txt

# Networks (optional)
networks:
  default:
    name: tandoor_network
    driver: bridge