name: Issue/PR Tracker

on:
  issues:
    types: [opened, reopened, labeled, closed]

jobs:
  issue-pr-tracker:
    if: ${{ !contains(github.actor, 'dependabot') }}
    uses: linuxserver/github-workflows/.github/workflows/issue-pr-tracker.yml@main
    permissions:
      contents: read
      issues: write
      pull-requests: write
    secrets: inherit
